version: '3.8'

services:
  api_gateway:
    container_name: api_gateway
    build: ./nginx
    networks:
      - crm
    ports:
      - "80:80"

  auth:
    container_name: auth
    build: .
    networks:
      - crm
    command: ["/drf_app/auth/run_auth.sh"]
    env_file:
      - ./.env
    depends_on:
      - auth_db

  auth_db:
    container_name: auth_db
    image: postgres:12.0-alpine
    networks:
      - crm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

networks:
    crm:
      name: crm-net

volumes:
  postgres_data: